title: Data Cloning
description: Hierarchical model made easy
#url:  http://localhost:4000
url: http://datacloning.github.io
#permalink:   /:categories/:title.html
#category: news

include: [".htaccess"]
exclude: ["README.md","LICENSE.md"]
timezone:    America/Edmonton

highlighter: pygments
#highlighter: null
#highlighter: rouge

#markdown: kramdown
#kramdown:
#  input:          GFM
#  hard_wrap:      false

markdown_ext: "markdown,mkdown,mkdn,mkd,md,Rmd"

markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
