title: Data Cloning
description: Hierarchical model made easy
#url:  http://localhost:4000
url: http://datacloning.github.io
#permalink:   /:categories/:title.html
#category: news

include: [".htaccess"]
exclude: ["README.md","LICENSE.md"]
timezone:    America/Edmonton

highlighter: pygments
#highlighter: rouge
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      false

markdown_ext: "markdown,mkdown,mkdn,mkd,md,Rmd"


